language: php

php:
  - 5.3.0
  - 5.3.1
  - 5.3.2
  - 5.3.3
  - 5.3.4
  - 5.3.5
  - 5.3.6
  - 5.3.7
  - 5.3.8
  - 5.3.9
  - 5.3.10
  - 5.4

env:
  - TRAVISCI=1

branches:
  only:
    - develop
    - master

notifications:
  email:
    - ci@andrewsville.cz

script: phpunit tests/TokenReflection